### ISSUE TITLE
Parameter passing

### ISSUE THREAD

**Issue by ansabsheikh9** [traveller59/kitti-object-eval-python#3]
Hi,
First of all, thank you for sharing your code. 
I am trying to evaluate my algorithm and on line 468 found you are calling a function with parameters:
     rets = calculate_iou_partly(dt_annos, gt_annos, metric, num_parts)
while the function is defined as: line 335
def calculate_iou_partly(gt_annos, dt_annos, metric, num_parts=50):
so gt_annos becomes dt_annos, kindly have a look
https://github.com/traveller59/kitti-object-eval-python/blob/40b36f6273ca461446ea13fe4213d0252b5f1fef/eval.py#L468

**Comment by johleh** [comment]
switching  gt_annos and dt_annos to 
rets = calculate_iou_partly(gt_annos, dt_annos, metric, num_parts)
crashes the kernel of the ipython notebook i use to test evaluation

**Comment by traveller59** [comment]
I don't notice the email of this issue, sorry.
the dt_annos and gt_annos should be exchangeable, exchange them will exchange result too. may be I should rename them to annos1 and annos2.
But in eval_class function they are't exchangeable because other codes treat gt and dt(detection) as different things.
